networks:
  network:
    driver: bridge

volumes:
  postgres:
  redis:
  n8n:
  n8n_tmp:

services:
  redis:
    image: redis:7.4
    command: redis-server --appendonly yes --appendfsync everysec --save "" --maxmemory-policy noeviction
    restart: unless-stopped
    networks:
      - network
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:18
    restart: unless-stopped
    networks:
      - network
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${DB_POSTGRESDB_DATABASE}
      - POSTGRES_USER=${DB_POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${DB_POSTGRESDB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_POSTGRESDB_USER} -d ${DB_POSTGRESDB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  n8n:
    image: n8nio/n8n:latest
    command: start
    restart: unless-stopped
    networks:
      - network
    volumes:
      - n8n:/home/node/.n8n
    env_file:
      - .env
    environment:
      - N8N_DISABLE_PRODUCTION_MAIN_PROCESS=true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  n8n_webhook:
    image: n8nio/n8n:latest
    command: webhook
    restart: unless-stopped
    networks:
      - network
    volumes:
      - n8n:/home/node/.n8n
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  n8n_worker:
    image: n8nio/n8n:latest
    command: worker --concurrency=10
    stop_grace_period: 60s
    restart: unless-stopped
    networks:
      - network
    volumes:
      - n8n:/home/node/.n8n
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  n8n_task_runner:
    image: n8nio/runners:latest
    restart: unless-stopped
    networks:
      - network
    environment:
      - N8N_RUNNERS_TASK_BROKER_URI=http://n8n_worker:5679
      - N8N_RUNNERS_AUTH_TOKEN=${N8N_RUNNERS_AUTH_TOKEN}
    depends_on:
      - n8n_worker

  cloudflare:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    restart: unless-stopped
    networks:
      - network
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
    depends_on:
      - n8n
      - n8n_webhook
      - n8n_worker
