global:
  scrape_interval: 15s

scrape_configs:
  - job_name: n8n-main
    static_configs:
      - targets: ['n8n:5678']
  - job_name: n8n-webhook
    static_configs:
      - targets: ['n8n_webhook:5678']
  - job_name: n8n-worker
    static_configs:
      - targets: ['n8n_worker:5678']
  - job_name: node
    static_configs:
      - targets: ['node_exporter:9100']
